<a href="https://colab.research.google.com/github/dheerajnalla09/AIML/blob/main/flight_fare_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Flight Fare Prediction using SVR and Random Forest
This notebook demonstrates how to predict flight fares using two machine learning models:
- **Support Vector Regression (SVR)**
- **Random Forest Regressor**

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Step 1: Load Dataset

In [2]:
data = {
    'airline': ['SpiceJet', 'SpiceJet', 'AirAsia', 'Vistara'],
    'flight': ['SG-8709', 'SG-8157', 'I5-764', 'UK-995'],
    'source_city': ['Delhi', 'Delhi', 'Delhi', 'Delhi'],
    'departure_time': ['Evening', 'Early_Morning', 'Early_Morning', 'Morning'],
    'stops': ['zero', 'zero', 'zero', 'zero'],
    'arrival_time': ['Night', 'Morning', 'Early_Morning', 'Afternoon'],
    'destination_city': ['Mumbai', 'Mumbai', 'Mumbai', 'Mumbai'],
    'class': ['Economy', 'Economy', 'Economy', 'Economy'],
    'duration': [2.17, 2.33, 2.17, 2.25],
    'days_left': [1, 1, 1, 1],
    'price': [5953, 5953, 5956, 5955]
}
df = pd.DataFrame(data)
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955

In [3]:
#df=pd.read_csv(r""C:\Users\admin\Documents\DS Class\ML\Superwised\Regression\SVR\Clean_Dataset.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   airline           4 non-null      object
 1   flight            4 non-null      object
 2   source_city       4 non-null      object
 3   departure_time    4 non-null      object
 4   stops             4 non-null      object
 5   arrival_time      4 non-null      object
 6   destination_city  4 non-null      object
 7   class             4 non-null      object
 8   duration          4 non-null      float64
 9   days_left         4 non-null      int64
 10  price             4 non-null      int64
dtypes: float64(1), int64(2), object(8)
memory usage: 484.0+ bytes

## Step 2: Preprocess Data

In [5]:
df.isnull().sum()

airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [6]:
print(df.columns)

Index(['airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price'],
      dtype='object')

In [7]:
for i in df.columns:
    print(i)

airline
flight
source_city
departure_time
stops
arrival_time
destination_city
class
duration
days_left
price

In [8]:
columns_names=df.columns.tolist()
print(columns_names)

['airline', 'flight', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class', 'duration', 'days_left', 'price']

In [9]:
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955

In [10]:
df.arrival_time

0            Night
1          Morning
2    Early_Morning
3        Afternoon
Name: arrival_time, dtype: object

In [11]:
categorical_cols = ['airline','flight','source_city','departure_time','stops','arrival_time','destination_city','class']
le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,1,2,0,1,0,3,0,0,2.17,1,5953
1,1,1,0,0,0,2,0,0,2.33,1,5953
2,0,0,0,0,0,1,0,0,2.17,1,5956
3,2,3,0,2,0,0,0,0,2.25,1,5955

## Step 3: Define Features and Target

In [12]:
X = df.drop(columns=['price'])
y = df['price']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [13]:
## Step 4: Train Models

In [14]:
svr = SVR(kernel='rbf', )
svr.fit(X_train, y_train)
y_pred_svr = svr.predict(X_test)

rf = RandomForestRegressor(random_state=42,n_estimators=100, max_depth=5)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

## Step 5: Evaluate Models

In [15]:
print('SVR Results:')
print('MAE:', mean_absolute_error(y_test, y_pred_svr))
print('MSE:', mean_squared_error(y_test, y_pred_svr))
print('R2:', r2_score(y_test, y_pred_svr))

print('\nRandom Forest Results:')
print('MAE:', mean_absolute_error(y_test, y_pred_rf))
print('MSE:', mean_squared_error(y_test, y_pred_rf))
print('R2:', r2_score(y_test, y_pred_rf))

SVR Results:
MAE: 1.010344468515541
MSE: 1.2475702542710638
R2: -0.24757025427106383

Random Forest Results:
MAE: 1.1199999999998909
MSE: 1.2832999999997803
R2: -0.2832999999997803